#!/usr/bin/env bash
# =============================================================================
# config.sh — Nanopore pipeline — PHAGE version (CLUSTER / Maestro)
# =============================================================================
# For a NEW RUN: edit SECTION 1 only (5 lines). Everything else is derived.
# Sections:
#   1. Run identification  ★ — edit per run
#   2. Derived paths       — auto-computed from Section 1
#   3. Tool databases      — shared across runs (edit once)
#   4. Analysis settings   — algorithm parameters (rarely need changing)
#   4b. Methylation analysis settings — step 07 parameters
#   5. Compute resources   — SLURM/hardware settings
#   6. Internal helpers    — functions, do not edit
# =============================================================================

# =============================================================================
# SECTION 1 — RUN IDENTIFICATION  ★ Edit this block for each new run
# =============================================================================

# Root directory containing all ONT runs on cluster storage (helix projects).
NANOPORE_BASE="/pasteur/helix/projects/Phage3C/_projects/Nanopore/"  # ★ storage root

# Folder name for THIS sequencing run.  Convention: YYYYMMDD_ONT_<description>
RUN_NAME="20260520_ONT_phages"  # ★ set for each run

# Your Institut Pasteur email for SLURM notifications (must be @pasteur.fr on Maestro)
EMAIL="csivelle@pasteur.fr"  # ★

# SLURM partition.  Leave empty → default 'common' (1-day limit, all nodes).
# Use 'long' for jobs >24h.
PARTITION=""   # ★ or "long"

# Project account if required by your allocation on Maestro (leave empty if not)
ACCOUNT=""     # ★ or "phage3c" etc.

# ── Sample names  ★ ──────────────────────────────────────────────────────────
# Map each barcode to a biological name.
# Format: space-separated list of  barcodeXX:name  pairs.
# Leave empty → names are auto-generated (phage01, phage02, …).
# Barcodes not listed here also get auto-generated names.
SAMPLE_NAMES_MAP="barcode01:PAK_P1 barcode02:PAK_P4 barcode03:CHA_P1_rec barcode04:PAK_P4_rec barcode05:PAK_P4_CHA"   # ★  e.g. "barcode01:OM144 barcode02:OM147 barcode03:LF73"

# Each barcode is analysed independently (no clone-vs-reference comparison).

# =============================================================================
# SECTION 2 — DERIVED PATHS  (auto-computed — do not edit)
# =============================================================================

RUN_DIR="${NANOPORE_BASE%/}/${RUN_NAME}"

# ONT FASTQ output from MinKNOW.
# MinKNOW writes fastq_pass/ directly at the root of the run folder.
FASTQ_PASS_DIR="${RUN_DIR}/fastq_pass"

# Optional: Illumina reads for hybrid polishing.
# If present, step 00 will offer hybrid mode for samples that have matching reads.
# Folder layout: barcodeXX_<name>/ containing R1/R2 fastq.gz files.
# Leave unchanged (empty string) to skip hybrid mode entirely.
ILLUMINA_DIR="${RUN_DIR}/reads_illumina"

# Sequencing summary directory (MinKNOW writes it at the run root)
SEQ_SUMMARY_DIR="${RUN_DIR}"

# Pipeline results
RESULTS_DIR="${RUN_DIR}/result_nanopore_optimisation"

# Sample sheet (auto-generated by step 00 — path shown here for reference)
SAMPLE_SHEET="${RESULTS_DIR}/sample_sheet.tsv"

# Per-barcode mod-base BAMs produced directly by MinKNOW
# (modification calling enabled at sequencing time via MinKNOW settings).
# MinKNOW demuxes BAMs into one file per barcode.
#
# Two supported layouts:
#   A) Flat directory:  MOD_DEMUX_DIR/barcode01.bam  (one BAM per barcode)
#   B) Subdirectories:  MOD_DEMUX_DIR/barcode01/*.bam (multiple chunks — merged by step 07)
#
# Leave empty → step 07 is skipped.
# NOTE (2026-07-08): now pointed at the RE-BASECALLED all-context demux (6mA+4mC+5mC,
# all contexts) so steps 06→07 analyse those calls, not the MinKNOW CpG-only BAMs.
# Step 06 finds the dorado-named files (<hash>_<kit>_barcodeNN.bam) via its Layout C
# wildcard. To revert to the original MinKNOW calls, set this back to "${RUN_DIR}/bam_pass".
MOD_DEMUX_DIR="${RUN_DIR}/bam_pass_rebasecalled_allcontext"

# =============================================================================
# SECTION 3 — TOOL DATABASES  (shared across runs — edit once after install)
# =============================================================================

# Pharokka annotation database.
# Install: pharokka_db_install.py --db_dir /path/to/pharokka_db
PHAROKKA_DB="/pasteur/helix/projects/Phage3C/_projects/databases/pharokka_db"  # ★
# Pharokka gene predictor for step 05: prodigal-gv (default, robust/consistent) or phanotate.
PHAROKKA_GENE_PREDICTOR="prodigal-gv"

# CheckV database (step 04 — assembly QC: completeness, contamination, host regions).
# Install once: checkv download_database /path/to/checkv  (creates checkv-db-vX.Y)
# Point CHECKV_DB at the versioned db directory. Leave empty → CheckV is skipped
# (coverage-uniformity QC still runs).
CHECKV_DB="/pasteur/helix/projects/Phage3C/_projects/databases/checkv-db"  # ★

# Micromamba environment name and root.
MAMBA_ENV="nanopore_phage"
MAMBA_ROOT_PREFIX="${HOME}/.mamba"

# Dorado binary + models directory (only needed for GPU re-basecalling, not required
# when MinKNOW already produces mod-tagged BAMs)
DORADO_BIN_DIR="/pasteur/helix/projects/Phage3C/_projects/tools/dorado"
# MUST be USER-WRITABLE: `dorado download` writes model weights here. The shared
# tools/ dir is read-only for regular users ("Insufficient permissions to download
# models"). Home works; if HOME quota is tight, use a dir under your run/project.
DORADO_MODELS_DIR="${HOME}/dorado_models"

# ── Re-basecalling for methylation (rebasecall_dorado.sh) ────────────────────
# Used ONLY when re-basecalling from POD5 to broaden modification coverage.
# MinKNOW here called 6mA + 5mCG_5hmCG (5mC CpG-only, no 4mC). To VERIFY the three
# canonical prokaryotic methylations in ALL contexts, re-basecall with the models
# below. SUP (not HAC) is recommended for modified-base accuracy.
DORADO_SIMPLEX_MODEL="dna_r10.4.1_e8.2_400bps_sup@v5.0.0"  # match chemistry (was HAC at seq time)
DORADO_MOD_BASES="6mA 4mC_5mC"   # all-context: 6mA + 4mC + 5mC (covers Dam/Dcm/R-M motifs)
# Dorado ≥0.7 auto-downloads ONLY when given a "model complex" (speed@version[,mods]).
# Passing the FULL model name makes dorado treat it as a local PATH and fail
# ("did not satisfy the model complex syntax ... Model does not exist at").
# So the basecaller is invoked with THIS complex (simplex + mods in one token):
DORADO_MODEL_COMPLEX="sup@v5.0.0,6mA,4mC_5mC"
# Raw signal directory (auto-detected under RUN_DIR if left empty: pod5_pass / pod5 / fast5_pass).
POD5_DIR=""
# Per-barcode mod-BAMs from re-basecalling land here. Kept SEPARATE from the
# MinKNOW bam_pass so the originals are never overwritten. Point MOD_DEMUX_DIR at
# this dir (above, Section 2) once re-basecalling succeeds, then rerun 06→07.
REBC_DEMUX_DIR="${RUN_DIR}/bam_pass_rebasecalled_allcontext"
# GPU partition on Maestro for the dorado basecaller job (check: sinfo -p gpu).
GPU_PARTITION="gpu"

# =============================================================================
# SECTION 4 — ANALYSIS SETTINGS  (algorithm parameters — rarely need changing)
# =============================================================================

# ── Assembly ─────────────────────────────────────────────────────────────────
# Approximate genome size for Flye (phage genomes are typically 40–200 kb).
# Used by Flye (--genome-size) and by the QC step for coverage estimation.
GENOME_SIZE_ESTIMATE="100k"

# Flye coverage subsampling for the initial disjointig stage.
# At ~10 000× (typical phage nanopore run), Flye benefits from subsampling.
# Set to 0 to disable subsampling and let Flye use all reads.
FLYE_ASM_COVERAGE=0      # superseded by FILTLONG_TARGET_COV (Filtlong caps input). Keep 0; set >0 only to also limit Flye's disjointig stage.

# Barcodes for which Flye should run with --meta mode.
# Recommended for samples where Direct Terminal Repeats (DTR) cause Flye to
# over-fragment the assembly in standard mode (symptom: 5–20 small contigs
# instead of a single circular genome).  --meta disables the repeat-graph
# simplification that trips on DTR junctions.
# Space-separated list of barcode IDs (NO commas).  Leave empty for standard mode on all.
FLYE_META_BARCODES="barcode02"   # ★  e.g. "barcode02" or "barcode02 barcode03 barcode04"

# ── Assembler choice (step 02) ───────────────────────────────────────────────
# 'autocycler' (recommended): multi-assembler consensus (Ryan Wick's successor to
#   Trycycler) — best assemblies for accurate termini / PhageTerm. Available on
#   Maestro via Lmod. Autocycler does its OWN read subsampling, so very high ONT
#   coverage is handled internally (Filtlong pre-cap is NOT applied in this mode).
# 'flye': single Flye assembly; input coverage is first capped to
#   FILTLONG_TARGET_COV with Filtlong (very high coverage degrades Flye).
# If 'autocycler' (or all its sub-assemblers) are unavailable, step 02 falls back
# to the Flye+Filtlong path automatically.
ASSEMBLER="autocycler"
# Autocycler sub-assemblers to try (auto-filtered to those actually installed).
AUTOCYCLER_ASSEMBLERS="flye raven miniasm plassembler"
# Tool source: prefer a dedicated micromamba env (fast/reproducible); else Lmod.
# Leave AUTOCYCLER_ENV empty to use the modules below.
AUTOCYCLER_ENV=""
AUTOCYCLER_MODULES="Flye raven minimap2 samtools/1.21 Autocycler/0.5.2"
# Per-sub-assembler wall-time cap (seconds). A hanging assembler is killed and
# skipped so it cannot consume the whole job walltime. Default 2700s (45 min).
AUTOCYCLER_HELPER_TIMEOUT=2700
# Flye path ONLY: cap input coverage to this depth with Filtlong before Flye
# (ignored under Autocycler). Set 0 to disable. ~100× is the recommended cap.
FILTLONG_TARGET_COV=100

# ── Optional host-read depletion (pre-assembly, step 01b) ────────────────────
# When true, an extra array step (01b) removes HOST-derived reads BEFORE assembly
# by competitive mapping of the QC'd ONT reads against HOST_REF together with any
# optional phage references (HOST_DEPLETE_PHAGE_REFS). Reads whose best alignment is to the host are
# dropped; phage-best and unmapped reads are kept. Orthogonal to Filtlong/Flye
# coverage handling. Use when CheckV/QC (step 04) flags host contamination or for
# poorly purified preps. Default OFF — the post-assembly <MIN_CONTIG_LEN filter
# already removes small host contigs in clean lytic-phage preps.
HOST_DEPLETION=false
# Bacterial host genome FASTA (e.g. Pseudomonas aeruginosa) for the competitive
# mapping. Required when HOST_DEPLETION=true.
HOST_REF=""   # ★  e.g. "/pasteur/helix/.../refs/Paeruginosa_PAK.fasta"
# OPTIONAL phage reference genome(s) to add to the competitive mapping so reads
# whose best hit is a phage are protected from depletion. Space-separated list of
# FASTA or GenBank paths (NO commas). Leave empty → host-only mapping (standard).
HOST_DEPLETE_PHAGE_REFS=""   # ★  e.g. "/path/PAK_P1.fasta /path/CHA_P1.gbk"

# ── Assembly strategy ────────────────────────────────────────────────────────
# ALL samples are assembled with Flye (ONT long reads define the structure).
# Illumina reads — when present — are used ONLY for short-read polishing in
# step 03 (Polypolish + Pypolca), never to build the assembly. This is the right
# choice for the very short (~50 bp native) Illumina libraries of this project:
# high depth refines bases in UNIQUE regions but cannot resolve structure across
# repeats/DTRs, so structure stays ONT-defined. (The former Unicycler hybrid +
# forced-single-contig SPAdes fallback have been REMOVED — they risked chimeric
# junctions at DTR boundaries.)
#
# A single contig is now a REPORTED QC metric, not an assembly target: the
# assembler output stands as-is. If a genome stays fragmented, step 02 exposes
# the assembly graph (for_bandage.gfa) for optional manual finishing in Bandage.
# See MANUAL_FINISHING.md for the exact procedure.

# ── Single-contig finishing (step 02) ────────────────────────────────────────
# finish_assembly.py detects terminal repeats (DTR) / circular overhangs and, if
# the assembly stays fragmented, exposes the assembly graph (for_bandage.gfa) for
# manual finishing in Bandage (see MANUAL_FINISHING.md). Trimming circular
# overhangs is OFF by default to protect real short phage DTRs (e.g. T7 ~160 bp);
# enable only if you are sure.
FINISH_TRIM_OVERHANG=false    # true → trim circular overhangs <= FINISH_CIRC_MAX
FINISH_CIRC_MAX=1000          # terminal repeat <= this = overhang; larger = DTR (kept)

# Parasite/contaminant filter (step 02 finishing): drop contigs shorter than this
# many bp (likely host fragments / debris). 35000 keeps a safe margin below ~40 kb
# phage genomes. SAFETY: skipped automatically if NO contig reaches the threshold
# (a fragmented genome is never wiped). Set 0 to disable.
MIN_CONTIG_LEN=35000

# ── Read quality filtering (chopper) ─────────────────────────────────────────
# Q12 is comfortable for R10.4.1: at 5 000–13 000× coverage the depth loss is
# irrelevant, while the cleaner read set improves the assembly and reduces
# downstream noise (raised from the previous Q10). Push to Q13–15 if desired.
MIN_READ_QUALITY=12     # Phred Q score minimum
MIN_READ_LENGTH=200     # Minimum read length in bp (shorter for phage reads)

# ── Medaka polishing model ────────────────────────────────────────────────────
# Must match the basecalling model used by MinKNOW.
MEDAKA_MODEL="r1041_e82_400bps_hac_v5.0.0"
# If re-basecalled with SUP model, change to: r1041_e82_400bps_sup_v5.0.0

# Hybrid samples: run Medaka (ONT consensus) on the Flye draft BEFORE the
# Illumina polishing (Polypolish + Pypolca). Correct order for Flye-based hybrid
# assemblies (long-read polish first, accurate short-read polish last). Set to
# "false" to skip and polish with Illumina only. Non-fatal if Medaka fails.
HYBRID_MEDAKA="true"

# ── Termini detection / reorientation (step 03) ──────────────────────────────
# PhageTerm characterises physical genome ends (DTR, cos, pac, headful…) from the
# read-mapping pattern and, when it finds a clear terminus, reorients the genome
# to it. dnaapler (terL gene) is the FALLBACK when PhageTerm is unavailable or
# inconclusive; finish_assembly.py DTR detection (step 02) is kept regardless.
# Set PHAGETERM_BIN to the PhageTerm executable (PhageTerm.py / phageterm), or
# leave empty to auto-detect in PATH. If absent, only dnaapler is used.
PHAGETERM_BIN=""
# Lmod module providing PhageTerm on the cluster (loaded by step 03 if PHAGETERM_BIN
# is empty and the binary is not already in PATH). Adjust the version if needed.
PHAGETERM_MODULE="PhageTerm"

# ── Coverage thresholds ───────────────────────────────────────────────────────
# Phage runs typically yield very high coverage (1 000–10 000×).
# These thresholds guard against accidentally processing nearly-empty barcodes.
MIN_COVERAGE_WARN=100   # Warn if coverage drops below this
MIN_COVERAGE_FAIL=20    # Abort assembly if below this

# Barcode kit name (used by split_modbam_by_minknow.py if needed)
BARCODE_KIT="SQK-NBD114-24"

# =============================================================================
# SECTION 4b — METHYLATION ANALYSIS SETTINGS  (step 07 — edit if needed)
# =============================================================================

# ── Coverage and delta thresholds ────────────────────────────────────────────
# Minimum read depth to consider a methylation site.
COV_MIN_METHYL=8

# Minimum absolute difference in % methylation to call a DMR.
DMR_DELTA=25

# MicrobeMod speed controls (step 07a). The mod-tagged BAM is at very high depth
# (5 000–13 000×); motif discovery (STREME) and the gene searches scale with the
# data, so MicrobeMod is run on a BAM SUBSAMPLED to ~MICROBEMOD_MAX_COV (well
# above COV_MIN_METHYL, so calls stay confident). A hard per-sample timeout caps
# the runtime; on timeout the barcode is skipped (non-fatal) and the gather step
# (07b) still runs. Set MICROBEMOD_MAX_COV=0 to disable subsampling.
# ── modkit 0.2.x (REQUIRED by MicrobeMod 1.1.0) ──────────────────────────────
# MicrobeMod 1.1.0 calls `modkit pileup … --only-tabs`. That flag was REMOVED in
# modkit ≥ 0.3, so the env/cluster modkit (currently 0.6.2) makes MicrobeMod fail
# with `error: unexpected argument '--only-tabs'` → exit 2 → rc=1. Install a
# pinned 0.2.x ONCE into its own micromamba env and point MODKIT_02X_BIN at it:
#   micromamba create -n modkit_0.2 -c bioconda -c conda-forge ont-modkit=0.2.6
# Step 07a then forces this binary to the FRONT of PATH (via use_modkit_02x) so
# MicrobeMod's internal `modkit` call resolves to 0.2.x, not the 0.6.2 in the env.
MODKIT_02X_BIN="${MAMBA_ROOT_PREFIX}/envs/modkit_0.2/bin/modkit"

MICROBEMOD_MAX_COV=300
# Hard per-barcode timeout for MicrobeMod call_methylation in 07a (seconds).
# MUST stay comfortably BELOW TIME_METHYL_CALL (the 07a SLURM walltime) so the
# internal `timeout` fires FIRST and writes a clean TIMEOUT sentinel, instead of
# SLURM SIGKILLing the task at the wall (which leaves no sentinel → invisible).
MICROBEMOD_TIMEOUT=28800   # seconds (8 h) — keep < TIME_METHYL_CALL
# Separate hard timeout for the subsampling pre-processing (samtools coverage +
# view -s) that runs BEFORE MicrobeMod. Bounded so a slow/huge BAM cannot eat the
# whole walltime and starve the MicrobeMod timeout.
MICROBEMOD_SUBSAMPLE_TIMEOUT=3600  # seconds (1 h)

# =============================================================================
# SECTION 5 — COMPUTE RESOURCES
# =============================================================================

THREADS=16
MAX_MEMORY_GB=64        # Flye RAM cap — phage genomes are small; 64 G is ample

# Walltimes per step (hh:mm:ss).  Maestro 'common' partition limit: 1 day.
TIME_SETUP="00:30:00"
TIME_QC="01:00:00"
TIME_HOSTDEPLETE="02:00:00"  # 01b (optional) competitive host-read depletion
TIME_ASSEMBLE="06:00:00"    # 02 Autocycler multi-assembler is heavier than single Flye
TIME_POLISH="06:00:00"      # 03 Medaka (ONT) [+ Polypolish + Pypolca if Illumina]
MEDAKA_MAX_COV=200          # downsample ONT reads to ~this depth for Medaka (speed; >200x adds nothing)
TIME_ASMQC="01:00:00"       # 04 assembly QC: CheckV + remap coverage uniformity
TIME_ANNOTATE="00:30:00"    # 05 Pharokka on phage: fast
TIME_MODBASE="02:00:00"     # 06 minimap2 alignment + modkit pileup
TIME_METHYL_CALL="10:00:00" # 07a MicrobeMod call_methylation, ONE barcode per array task
                            #    (parallel → a long per-task wall is cheap). Must be
                            #    > MICROBEMOD_TIMEOUT + MICROBEMOD_SUBSAMPLE_TIMEOUT margin.
TIME_METHYL="02:00:00"      # 07b methylation GATHER only: reuses 07a TSVs, then stats +
                            #    annotation + HTML. Fast — never calls MicrobeMod.
TIME_SUMMARY="00:30:00"     # 09 run summary TSV/TXT/HTML
TIME_FINAL_REPORT="00:30:00" # 10 per-sample + global HTML report

# =============================================================================
# SECTION 6 — INTERNAL HELPERS  (do not edit below this line)
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STEPS_DIR="${SCRIPT_DIR}/steps"

log()         { echo "[$(date '+%H:%M:%S')] $*"; }
die()         { echo "[ERROR] $*" >&2; exit 1; }
warn()        { echo "[WARN]  $*" >&2; }

step_banner() {
    echo ""
    echo "════════════════════════════════════════════════════════"
    echo "  $*"
    echo "  $(date '+%Y-%m-%d %H:%M:%S')"
    echo "════════════════════════════════════════════════════════"
}

check_file() { [[ -f "$1" ]] || die "Required file not found: $1"; }
check_dir()  { [[ -d "$1" ]] || die "Required directory not found: $1"; }

require_tool() {
    command -v "$1" &>/dev/null \
        || die "Tool not found: $1 — is '${MAMBA_ENV}' micromamba env active?"
}

activate_env() {
    if [[ "${MAMBA_DEFAULT_ENV:-}" == "${MAMBA_ENV}" ]]; then return; fi

    local mamba_bin="${MAMBA_ROOT_PREFIX}/bin/micromamba"

    if [[ ! -x "${mamba_bin}" ]]; then
        die "micromamba not found at ${mamba_bin}.
    Run 00_install_env.sh first, or set MAMBA_ROOT_PREFIX in config.sh.
    Default install location: \${HOME}/.mamba"
    fi

    export MAMBA_ROOT_PREFIX
    eval "$("${mamba_bin}" shell hook --shell bash)"
    micromamba activate "${MAMBA_ENV}" \
        || die "Cannot activate micromamba env '${MAMBA_ENV}'.
    Create it with: bash 00_install_env.sh"
}

# Load samtools from the Maestro cluster module system.
# The samtools bundled inside the micromamba env is prehistoric (< 0.1.19)
# and does not support `--version`, `sort -O`, `coverage`, etc.
# Maestro ships samtools/1.21 via Lmod.
#
# CONCURRENCY-SAFE: we NEVER mutate the shared micromamba env binary (the old
# version rewrote ${env}/bin/samtools with a wrapper, so parallel array tasks
# raced on the same file and could corrupt it mid-run). Instead we expose the
# module's samtools through a PER-PROCESS wrapper directory created with
# `mktemp -d` and PREPENDED to PATH — private to this task, cleaned up on exit.
# Falls back silently to the env samtools if the module system is absent (local dev).
load_samtools_cluster() {
    command -v module &>/dev/null || {
        echo "[WARN] module system not available — using env samtools (may be outdated)" >&2
        return 0
    }

    module load samtools/1.21 2>/dev/null \
        || module load samtools 2>/dev/null \
        || { echo "[WARN] module load samtools failed — using env samtools (may be outdated)" >&2; return 0; }

    local module_st
    module_st=$(command -v samtools 2>/dev/null)
    local env_st="${MAMBA_ROOT_PREFIX}/envs/${MAMBA_ENV}/bin/samtools"

    if [[ -n "${module_st}" && "${module_st}" != "${env_st}" ]]; then
        local wrap_dir
        wrap_dir=$(mktemp -d "${TMPDIR:-/tmp}/samtools_wrap_XXXXXX")
        ln -sf "${module_st}" "${wrap_dir}/samtools" 2>/dev/null \
            || { printf '#!/bin/bash\nexec "%s" "$@"\n' "${module_st}" > "${wrap_dir}/samtools"; chmod +x "${wrap_dir}/samtools"; }
        export PATH="${wrap_dir}:${PATH}"
        trap 'rm -rf "'"${wrap_dir}"'"' EXIT
    fi

    local st_ver
    st_ver=$(samtools --version 2>&1 | head -1 || echo "unknown")
    echo "[INFO] samtools active: ${st_ver}  (path: $(command -v samtools 2>/dev/null))"
}

# Force modkit 0.2.x to the FRONT of PATH for MicrobeMod (which needs the
# `--only-tabs` flag removed in modkit ≥ 0.3). Same concurrency-safe pattern as
# load_samtools_cluster: a PER-PROCESS wrapper dir (never mutates a shared env).
# Returns non-zero (and warns loudly) if MODKIT_02X_BIN is missing — the caller
# stays non-fatal so the failure is still recorded by the sentinel logic.
use_modkit_02x() {
    local bin="${MODKIT_02X_BIN:-}"
    if [[ -z "${bin}" || ! -x "${bin}" ]]; then
        warn "modkit 0.2.x not found at MODKIT_02X_BIN='${bin}'."
        warn "  MicrobeMod 1.1.0 needs modkit 0.2.x (--only-tabs). Install once:"
        warn "  micromamba create -n modkit_0.2 -c bioconda -c conda-forge ont-modkit=0.2.6"
        return 1
    fi
    local ver
    ver=$("${bin}" --version 2>&1 | head -1 || echo "unknown")
    case "${ver}" in
        *0.2.*) : ;;
        *) warn "MODKIT_02X_BIN reports '${ver}' (expected 0.2.x) — MicrobeMod may still fail on --only-tabs." ;;
    esac
    local d
    d=$(mktemp -d "${TMPDIR:-/tmp}/modkit02_XXXXXX")
    ln -sf "${bin}" "${d}/modkit" 2>/dev/null \
        || { printf '#!/bin/bash\nexec "%s" "$@"\n' "${bin}" > "${d}/modkit"; chmod +x "${d}/modkit"; }
    export PATH="${d}:${PATH}"
    echo "[INFO] modkit active: ${ver}  (path: $(command -v modkit 2>/dev/null))"
}

# Read a field from the sample sheet by barcode
get_sample_field() {
    local barcode="$1" field="$2"
    local header idx value
    header=$(grep -v '^#' "${RESULTS_DIR}/sample_sheet.tsv" | head -1)
    idx=$(echo "$header" | tr '\t' '\n' | grep -n "^${field}$" | cut -d: -f1)
    [[ -z "$idx" ]] && die "Field '${field}' not found in sample_sheet.tsv"
    value=$(grep "^${barcode}"$'\t' "${RESULTS_DIR}/sample_sheet.tsv" \
              | cut -f"${idx}")
    echo "$value"
}

# List all barcodes in the sample sheet (skipping header and comment lines)
list_barcodes() {
    grep -v '^#' "${RESULTS_DIR}/sample_sheet.tsv" \
        | tail -n +2 \
        | cut -f1
}

# Count barcodes in the sample sheet
count_barcodes() {
    list_barcodes | wc -l | tr -d ' '
}
